on:
  push:
    branches:
      - cicd-docker-ec2

jobs:
  build:
    name: CICD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_USERPASSWORD }}
      
      - name: Build Docker image
        run: docker build -t ntakadza/saas-translation-app .
      
      - name: Publish image to Docker Hub
        run: docker push ntakadza/saas-translation-app:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ntakadza/saas-translation-app:latest
      
      - name: Delete old container
        run: docker rm -f saas-translation-app-container
      
      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name saas-translation-app-container ntakadza/saas-translation-app

