name: CICD

on:
  push:
  branches: [cicd-docker-ec2]

  jobs: 
    build:
     runs-on: [ubuntu-latest]
       steps:
          - name: Checkout source
            uses: actions/checkout@v3
          - name: Login to docker hub
            run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD}}
          - name: Build docker image
            run: docker build -t ntakadza/saas-translation-app
          - name: Publish image tp docker hub
            run:  docker push  ntakadza/saas-translation-app:latest 

   deploy: 
     need: build
     runs-on: [aws-ec2]
     steps: 
     - name: Pull image from docker hub
     run: docker pull ntakadza/saas-translation-app:latest 
     name: Delete old container
     run: docker rm -f saas-translation-app-container
     -name: Run docker container
     run: docker run -d -p 3000:3000 -name saas-translation-app-container ntakadza/saas-translation-app